"""genus care cache

Revision ID: 2de229379291
Revises: 09c01886d0df
Create Date: 2026-07-04 10:10:54.927461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de229379291'
down_revision: Union[str, Sequence[str], None] = '09c01886d0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genus_care_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genus', sa.String(length=150), nullable=False),
    sa.Column('source_slug', sa.String(length=150), nullable=True),
    sa.Column('sunlight', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genus')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genus_care_cache')
    # ### end Alembic commands ###
