"""initial schema

Revision ID: be5fa8415e3c
Revises: 
Create Date: 2026-07-03 19:18:08.716002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5fa8415e3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('family', sa.String(length=150), nullable=True),
    sa.Column('genus', sa.String(length=150), nullable=True),
    sa.Column('watering_frequency', sa.String(length=100), nullable=True),
    sa.Column('sunlight', sa.String(length=200), nullable=True),
    sa.Column('growth_rate', sa.String(length=50), nullable=True),
    sa.Column('origin_region', sa.String(length=100), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('reference_image_url', sa.String(length=500), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plant_species_family', 'plant_species', ['family'], unique=False)
    op.create_index('ix_plant_species_genus', 'plant_species', ['genus'], unique=False)
    op.create_index('ix_plant_species_origin_country', 'plant_species', ['origin_country'], unique=False)
    op.create_index('ix_plant_species_origin_region', 'plant_species', ['origin_region'], unique=False)
    op.create_index('ux_plant_species_source_external', 'plant_species', ['data_source', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['plant_species.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plants_species_id', 'plants', ['species_id'], unique=False)
    op.create_index('ix_plants_user_id', 'plants', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plant_photos_plant_id', 'plant_photos', ['plant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plant_photos_plant_id', table_name='plant_photos')
    op.drop_table('plant_photos')
    op.drop_table('sessions')
    op.drop_index('ix_plants_user_id', table_name='plants')
    op.drop_index('ix_plants_species_id', table_name='plants')
    op.drop_table('plants')
    op.drop_table('users')
    op.drop_index('ux_plant_species_source_external', table_name='plant_species', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('ix_plant_species_origin_region', table_name='plant_species')
    op.drop_index('ix_plant_species_origin_country', table_name='plant_species')
    op.drop_index('ix_plant_species_genus', table_name='plant_species')
    op.drop_index('ix_plant_species_family', table_name='plant_species')
    op.drop_table('plant_species')
    # ### end Alembic commands ###
