"""rich species fields

Revision ID: c8f3fcef02dc
Revises: be5fa8415e3c
Create Date: 2026-07-04 00:07:31.445154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f3fcef02dc'
down_revision: Union[str, Sequence[str], None] = 'be5fa8415e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_species', sa.Column('other_name', sa.String(length=500), nullable=True))
    op.add_column('plant_species', sa.Column('watering_benchmark', sa.String(length=50), nullable=True))
    op.add_column('plant_species', sa.Column('cycle', sa.String(length=50), nullable=True))
    op.add_column('plant_species', sa.Column('hardiness_min', sa.String(length=10), nullable=True))
    op.add_column('plant_species', sa.Column('hardiness_max', sa.String(length=10), nullable=True))
    op.add_column('plant_species', sa.Column('care_level', sa.String(length=50), nullable=True))
    op.add_column('plant_species', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('plant_species', sa.Column('drought_tolerant', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('indoor', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('poisonous_to_humans', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('poisonous_to_pets', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('cones', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('flowers', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('fruits', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('leaf', sa.Boolean(), nullable=True))
    op.add_column('plant_species', sa.Column('details_fetched', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_species', 'details_fetched')
    op.drop_column('plant_species', 'leaf')
    op.drop_column('plant_species', 'fruits')
    op.drop_column('plant_species', 'flowers')
    op.drop_column('plant_species', 'cones')
    op.drop_column('plant_species', 'poisonous_to_pets')
    op.drop_column('plant_species', 'poisonous_to_humans')
    op.drop_column('plant_species', 'indoor')
    op.drop_column('plant_species', 'drought_tolerant')
    op.drop_column('plant_species', 'description')
    op.drop_column('plant_species', 'care_level')
    op.drop_column('plant_species', 'hardiness_max')
    op.drop_column('plant_species', 'hardiness_min')
    op.drop_column('plant_species', 'cycle')
    op.drop_column('plant_species', 'watering_benchmark')
    op.drop_column('plant_species', 'other_name')
    # ### end Alembic commands ###
